### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by cymplecy** [AllAboutCode/EduBlocks#1]
Need the ability to save and load an edublock script

**Comment by AllAboutCode** [comment]
Self Assigned

**Comment by davidferguson** [comment]
### Technical aspects of importing/exporting:

#### For saving:

Part 1 is getting the data into a format that can be saved. This is easy, as Blockly has the ability to convert all the blocks on the workspace to XML code. (this is what PiBakery uses to export and import recipe files)

Part 2 is actually saving the XML data to a file. Only very very few browser support this natively at the moment, but it can be achieved with the excellent [filesaver.js](https://github.com/eligrey/filesaver.js) library. Basically it allows you to say what data you want to save (in your case it would be the variable containing the blockly XML data) and then it will present the user with a Save File dialog. I don't have time to get a demo of this working - but I may have more time later in the week.

#### For loading:

Part 1 is getting the XML data into a variable on the web page. Modern browsers do have access for reading files, but I'm not sure if the Pi's browser is new enough for this. You'll need to check if it supports the `FileReader` interface. I've setup a [test for you to run on the Raspberry Pi browser](https://jsfiddle.net/g2cu2xod/) (don't have access to any of my Pis at the moment) - could you see what happens when you click the `Choose File` button and then select a text file?

Part 2 is loading the XML from the variable into Blockly. This is very simple, and from memory is a single line of code.

----

### Overview of what the user sees:

For exporting:

1. User clicks save button
2. JavaScript is used with Blockly to generate an XML version of the block in the workspace, this is saved into a variable
3. [filesaver.js](https://github.com/eligrey/filesaver.js) is used to write a file containing the XML code to the Pi.

For importing:

1. User clicks `Choose File` button and selects XML file
2. File is imported using `FileReader` interface (if it works on Pi browser)
3. XML is then converted into a Blockly workspace.

----

This is essentially exactly what I did with PiBakery, and it should work for you. If I have time later this week I might be able to make some of the changes I suggested above and submit a pull request for them - but no guarantees!

David

**Comment by AllAboutCode** [comment]
Hi All, 
Thanks for the issue. Me and Chris Dell @cjdell (EduBlocks Developer) have created the basis of a Save and Load function which can be found in the Open and Save branch. We have added the functions to the main download and we are looking to create a developers version in the coming days/weeks. I am closing this issue and may re-open when we get a more advance function. I will create a guide on how to save and load but basically drag some blocks, click save, name the file, click OK, CTRL+S and chosenfilename.xml

For time being enjoy the Save and Load functions. Feel free to add any more issues.

Remember, Keep Coding.

EduBlocks Team
