### ISSUE TITLE
RangeError: Maximum call stack size exceeded while building UI

### ISSUE THREAD

**Issue by niutech** [AllAboutCode/EduBlocks#120]
I wanted to build the latest `beta-features` branch on my Windows 10 machine. I was able to build the server successfully, but I struggle to build the UI using `yarn run build`:
```
$ tsc && browserify -t brfs -t folderify build/main.js -o dist/main.js
events.js:1
// Copyright Joyent, Inc. and other Node contributors.
^

RangeError: Maximum call stack size exceeded
    at Stream.emit (events.js:1:1)
    at Stream.<anonymous> (C:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:215:7)
    at Stream.<anonymous> (C:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:215:7)
    at Stream.<anonymous> (C:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:215:7)
    at Stream.<anonymous> (C:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
    at Stream.emit (events.js:215:7)
    at Stream.<anonymous> (C:\EduBlocks\ui\node_modules\folderify\lib\folderify.js:144:16)
error Command failed with exit code 1.
```
Edublocks: 3.0.0
Node: 12.13.1
Yarn: 1.21.1

What could be the reason and how to fix it? Thank you!

**Comment by JoshuaLowe1002** [comment]
Hi there!

We don't support development on Windows machines directly due to the process being much easier by installing Windows Subsystem for Linux. Instead, please install Ubuntu 18.04 LTS via the Windows Store which will give you a bash terminal. This is becoming the recommended way to develop on Windows and it's what I use to develop EduBlocks myself. 

Please follow these instructions here to get setup https://github.com/AllAboutCode/EduBlocks/tree/beta-features#linux-install-instructions, however, I haven't yet tested them full/updated them for the BETA release so you may run into some errors. Please report back with any errors you get and how you fixed them, these will help me improve these instructions for the BETA release.

Josh

**Comment by niutech** [comment]
The error occures only when using `-t folderify`, which is used for `registerSamples()`, so I just commented out this code and omitted folderify from browserify and now it builds successfully.

**Comment by JoshuaLowe1002** [comment]
Install instructions should work now

**Comment by niutech** [comment]
I still have this error with the latest `master` branch.

**Comment by JoshuaLowe1002** [comment]
Currently rebuilding the entire project using Vue JS which means that people who want to install the project on their own machines will be made much simpler. No more work is being committed to the live project and full focus is on the rewrite, should be out next month or the month after
